### ISSUE TITLE
启用flush插件后，加载超过2层全依赖的模块，callback不触发

### ISSUE THREAD

**Issue by lianqin7** [seajs/seajs-flush#2]
``` js
// a.js
define('a', ['./b'], function(require){
    require('./b');
});

// b.js
define('b', ['./c'], function(require){
    require('./c');
});

// c.js
define('c', [], function(require){
    return 'c';
});

seajs.use('a', function(){
    alert('我不触发！');
});
seajs.flush()
```

**Comment by lifesinger** [comment]
要 `seajs.flush()`  一下

**Comment by lianqin7** [comment]
@lifesinger issue里忘记写了。。示例里有的。。

**Comment by lianqin7** [comment]
@lifesinger 终于发现最简单现场了 **超过2层的依赖不会触发！！**

**Comment by lifesinger** [comment]
问题应该出在内联代码上，如果模块代码内联，就没了下载过程，也就没有 requested 事情，导致依赖没被 flush 出来加载。最简单的重现代码：

``` html
<script>

// 内嵌代码，或通过 script 同步引入
define('zz', [], {})

// use 加载之
seajs.use('zz', function() { alert('为什么不触发我') })

// flush 之
seajs.flush()
</script>
```

我想想怎么解决。

**Comment by lianqin7** [comment]
@lifesinger 

不仅仅是内联的，我所有的模块定义（define）都是独立的文件，但是依赖的层数 **超过2层** （比如 a -> b -> c） 且是 **全依赖** （ a 的 deps 是 ['b', 'c']） 就会失败（原因应该是 propotype 上的 load 被修改了，超过2层的 load 触发之后却没有触发 flush），
issue里那么写只是简单地描述。。。

**Comment by lianqin7** [comment]
先reopen，等玉伯更美好的解决方案

**Comment by lifesinger** [comment]
这次应该解决了。内嵌模块的依赖不触发的问题，与多层级依赖时不触发的问题，是同一个问题。参考最新 flush 源码。测试代码在：

https://github.com/seajs/seajs/blob/master/tests/specs/extensible/seajs-flush/test.html

**Comment by billwing** [comment]
@lifesinger 我这里两层嵌套还是有问题，已经更新到2.1.1

HTML:

```
<script src="<?php echo $static['js'] ?>seajs/2.1.1/sea.js,seajs/2.1.1/seajs-combo.js,
seajs/2.1.1/seajs-flush.js,seajs/2.1.1/seajs-text.js"></script>
<script src="<?php echo $static['js'] ?>test/config.js"></script>
<script>
    seajs.use('test/main');
    // The combined request
    seajs.flush();
</script>
```

main.js:

```
define(function(require) {

    var $ = require('$');

    if($('#J-newsSlide').length) {
        // slide
        var Slide = require('slide');
        var newsSlide = new Slide({
        element: '#J-newsSlide',
        panels: '#J-newsSlide .ui-switchable-content li',
        effect: 'fade',
        easing: 'easeOutStrong',
        interval: 2000
        }).render();
    }
```

});

config.js 就不贴了，应该没问题的

问题：`TypeError: Slide is not a constructor`
貌似·slide`的依赖`switchable`没加载到，请问这个应该怎么解决呢？

**Comment by lifesinger** [comment]
能否贴一下 config？感觉不是 flush 的问题，而是 slide 的依赖路径问题。控制台中，看下 seajs.cache 里，switchable 的路径是否正确。

**Comment by billwing** [comment]
seajs.cache 找不到switchable
难道是slide里面`var Switchable = require('./switchable');`这里的问题？

config.js

```
// component
'switchable': 'lib/switchable/0.9.15/switchable',
'tabs': 'lib/switchable/0.9.15/tabs',
'slide': 'lib/switchable/0.9.15/slide',
```

**Comment by lianqin7** [comment]
@Billwing 别名不能用相对路径

**Comment by billwing** [comment]
![seajscache](https://f.cloud.github.com/assets/3411815/846494/b26b5e20-f412-11e2-9f2e-c02541dc06da.png)

貌似header.js和main.js里面的依赖都找不到

@lianqin7 我已经改了`var Switchable = require('switchable');`，还是不行。。

**Comment by billwing** [comment]
@lifesinger 玉伯，另外有个问题还想请教一下，其实之前有提到过，就是说我`config`里面引入了多个文件，怎么才能比较好的把他们`合并`成一个文件呢，但如果提前将它们`打包`成一个文件，那么依赖引入会不会有问题呢？而且每个项目引入的库文件可能又不相同，有没有更好的方案去处理这个问题呢？

config:

```
seajs.config({

    // 别名配置
    alias: {
        '$': 'core/jquery/1.8.3/jquery',

        // base
        'base': 'lib/base/1.1.1/base',
        'class': 'lib/class/1.1.0/class',
        'events': 'lib/events/1.1.0/events',
        'widget': 'lib/widget/1.1.1/widget',

        // tool
        'easing': 'lib/easing/1.0.0/easing',
        'iframe-shim': 'lib/iframe-shim/1.0.2/iframe-shim',
        'position': 'lib/position/1.0.1/position',
        'placeholder': 'lib/placeholder/1.0.1/placeholder',
        'templatable': 'lib/templatable/0.9.1/templatable',

        // component
        'switchable': 'lib/switchable/0.9.15/switchable',
        'tabs': 'lib/switchable/0.9.15/tabs',
        'slide': 'lib/switchable/0.9.15/slide',
        'autocomplete': 'lib/autocomplete/1.2.2/autocomplete',
        'select': 'lib/select/0.9.5/select',
        'dialog': 'lib/dialog/1.1.2/dialog',
        'confirmbox': 'lib/dialog/1.1.2/confirmbox',
        'overlay': 'lib/overlay/1.1.2/overlay',
        'mask': 'lib/overlay/1.1.2/mask',
        'popup': 'lib/popup/1.1.1/popup',

        // gallery
        'handlebars': 'gallery/handlebars/1.0.2/handlebars',

        // index

    },

    // 路径配置
    paths: {
    },

    // 变量配置
    vars: {
    },

    // 映射配置
    map: [
    ],

    // 预加载项
    preload: [
    ],

    // 调试模式
    debug: true,

    // Sea.js 的基础路径
    //base: '',

    // 文件编码
    charset: 'utf-8'
});
```

**Comment by lifesinger** [comment]
> 就是说我config里面引入了多个文件，怎么才能比较好的把他们合并成一个文件呢，但如果提前将它们打包成一个文件，那么依赖引入会不会有问题呢？而且每个项目引入的库文件可能又不相同，有没有更好的方案去处理这个问题呢？

用 Grunt 的 concat task，按照自己的需求，合并就好。针对你的项目，我的想法是：
1. 可以把各个项目都引用的库文件合并成一个问题，比如 base 和 tools 哪些，合并成一个，提前引入好就行，后续代码该怎么用还是怎么用，只是不会单独发请求了。
2. 各个项目特定的模块，如果服务器上有 combo 支持，可以加载 seajs-combo 插件，默认情况下，合并效果已经还可以，除非有特殊要求，一般不需要再处理。

**Comment by billwing** [comment]
好的，我后面试一下
回到第一个问题怎么解决呢
https://github.com/seajs/seajs-flush/issues/2#issuecomment-21459799
还有，发现`seajs-text`与跨越问题，我去`seajs-text`提issue好了

**Comment by lifesinger** [comment]
第一个问题信息不足，还不知道你遇到的是什么问题。最好能通过 jsfiddle.net 或 github 等方式，提供可重现问题的版本。

seajs-text 不能跨域的，这个是硬伤，浏览器级限制。一般开发时使用 seajs-text，上线后，所有模板等文本文件，都提前编译成 js 文件，这样来解决跨域问题。
