### ISSUE TITLE
flush的透明化

### ISSUE THREAD

**Issue by lianqin7** [seajs/seajs-flush#3]
**这个只是一个建议**

启用 flush 插件后，每次 `seajs.use` 之后都要跟着 `seajs.flush`  **不方便也不透明。**

在我们团队这边是这么做的：
1. 在 domReady 的时候默认调用一次 seajs.flush
2. domReady 之后的 seajs.use 功能和原来一致，就不做缓存了

domReady的判断，用了一段内联代码解决，代码量也不大

这样做之后：
1. 对于普通开发人员，根本不需要关心 seajs.flush 接口
2. 对于性能优化人员，在需要的地方调用 seajs.flush 就好

**Comment by lifesinger** [comment]
这个，也想过。目前我们用 jQuery，建议是 flush 插件后面，自己写一个 

```
$(document).ready(seajs.flush)
```

domReady 的判断还是比较麻烦的，网上流行的那段代码不是很好。
