### ISSUE TITLE
flush插件在单层依赖情况下的callback不能触发的bug

### ISSUE THREAD

**Issue by lianqin7** [seajs/seajs-flush#6]
在只有单层依赖（ **我们开发的时候用的是这种模式** ）的情况下，也会出现callback不能触发的bug，不过示例有点复杂，我 **尽量简单** 的还原了现场。 @lifesinger 玉伯有空看一下吧。

虽然单层依赖的使用场景较少，但是毕竟是个bug：（

case放在这里了：https://github.com/lianqin7/flush-case

**Comment by lifesinger** [comment]
这个是 flush 之后，带来了循环依赖，囧呢
我想想怎么解决

**Comment by lifesinger** [comment]
解决了。

@lianqin7 更新下 sea.js 和 seajs-flush.js

**Comment by lianqin7** [comment]
在实际使用中还是有问题，先open，我还原下实际现场

**Comment by lianqin7** [comment]
case更新了：https://github.com/lianqin7/flush-case

我想到一个解决方案，等会pull过来，玉伯看看是否合适
