### ISSUE TITLE
使用flush插件后，某些情况require.async会失效的问题

### ISSUE THREAD

**Issue by lianqin7** [seajs/seajs-flush#9]
https://github.com/seajs/seajs/issues/825

上面issue里的情况下，flush插件对 require.async 没有做处理，请求无法发出。

**Comment by lianqin7** [comment]
代码直接贴这里：

``` js
define(function(require){
    var $ = require('$');

    // ...

    // 点击某个按钮的时候去加载另一个模块
    $('button').click(function(){
        require.async('other/moudle', function(){
            // do something
        });
    });

});
```

**Comment by lifesinger** [comment]
这个有点头疼了，好像应该在执行 factory 之后，重置 requre.async 方法，让它自动 flush

不知道怎么处理才合适。

或者像 ICBU 的处理一样，dom ready 后，直接还原 use 和 async 。

**Comment by lianqin7** [comment]
@lifesinger  如果能在 `exec` 事件里对 `requre.async` 进行hack，就能解决这个问题了。。

**Comment by lifesinger** [comment]
调整为：

require.async 不加入 flush 逻辑

flush 只影响 seajs.use 和 deps 的加载。
